In [70]:
import numpy as np

# Домашнее задание на повторение numpy
В задании все пункты необходимо выполнить с помощью numpy, без использования циклов/map/и тд! 

Задание выполняется __самостоятельно__. «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, __у кого__ списали) не могут получить за него больше 0 баллов.

### История

В конце каждого семестра каждый семинарист сталкивается с необходимостью выставить студентам накопленную в семестре оценку. Часто семинаристы делают это с помощью Excel или GoogleSheets, но поверьте, с этим возникают проблемы. В задании вам надо помочь семинаристу курса XXX выполнить эту непростую работу с помощью numpy :)

Выполните ячейку ниже, чтобы загрузить данные и визуально проверить корректность их считывания.

По строкам - студенты, по столбцам - их оценки. В курсе семинарист провел три проверочных (первые три колонки), выдал три домашних работы (следующие три колонки), кроме того, у студентов есть оценка за коллоквиум (последняя колонка).

In [71]:
marks = np.loadtxt("https://raw.githubusercontent.com/nadiinchi/iad2019/master/materials/data_hw1.txt")

In [72]:
marks[:3]

array([[ 7. ,  8. , 10. ,  0. ,  0. ,  2.1,  1.5],
       [ 0. ,  6. ,  4.4,  4. ,  0. ,  5. ,  4.3],
       [ 3. ,  7. ,  8.7,  7.6,  7. ,  9.7, 10. ]])

### Число студентов (1 балл)
Сколько студентов в группе семинариста?

In [73]:
# Записать ответ в переменную num_studs
num_studs = num_studs = marks.shape[0] #число студентов = количество строк массива, которое стоит первым в кортеже размерности массива

In [74]:
print(num_studs)

28


### Очень сложная проверочная, или просто добрый семинарист (1.5 балла)
Семинарист помнит, что первая проверочная получилась очень сложной, и максимальный балл в группе был далеко не 10. Поэтому он решил перенормировать баллы за эту проверочную на максимум по группе (поделить на максимум и умножить на 10) - чтобы у студента с максимальной оценкой получилось 10, а у остальных - просто оценка больше.

Каков максимальный балл за первую проверочную?

In [75]:
# Записать ответ в переменную max_mark
max_mark = max(marks[:, 0]) # считаем максимум в первом столбце

In [76]:
print(max_mark)

7.0


Разделите первый столбец на max_mark (для этого надо выделить столбец, поставить после соответствующего выражения знак = и присвоить новое значение столбца)

In [77]:
x = (10 / max_mark) * marks[:, 0] # отнормировываем максимум к 10 через умножение строки на число

In [78]:
marks[:, 0] = x #меняем исходный массив

In [79]:
marks

array([[10.        ,  8.        , 10.        ,  0.        ,  0.        ,
         2.1       ,  1.5       ],
       [ 0.        ,  6.        ,  4.4       ,  4.        ,  0.        ,
         5.        ,  4.3       ],
       [ 4.28571429,  7.        ,  8.7       ,  7.6       ,  7.        ,
         9.7       , 10.        ],
       [ 4.85714286,  1.3       ,  7.        ,  3.4       ,  0.        ,
         9.4       ,  9.        ],
       [ 9.71428571,  9.1       ,  8.2       ,  0.        ,  0.        ,
         7.9       ,  7.9       ],
       [10.        , 10.        , 10.        ,  9.        ,  9.5       ,
        10.        ,  8.        ],
       [ 8.57142857, 10.        ,  9.7       ,  8.7       ,  7.        ,
         8.5       ,  9.7       ],
       [ 0.        ,  9.3       ,  5.7       ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 7.14285714, 10.        , 10.        ,  9.9       , 10.5       ,
        10.        ,  9.        ],
       [ 0.        ,  8.7   

### Подсчет накопленной оценки (1.5 балла)
Для вычисления накопленной надо посчитать средние оценки за проверочные для каждого студента и средние за домашние работы (может пригодиться np.mean). Накопленная оценка есть 0.3\*Проверочные + 0.4\*Домашние + 0.3\*Коллоквиум. Вычислите накопленные оценки и добавьте их в последний столбец матрицы (нужно добавить еще один новый столбец).

In [80]:
# Веса следует брать из переменной weights, а не вписывать вручную
weights = [0.3, 0.4, 0.3]

In [81]:
marks_prover = marks[:, :3] #выделяем проверочные
avprov = np.mean(marks_prover, axis=1) #находим средние по проверочным по каждой строке

In [82]:
marks_dom = marks[:, 3:6] #выделяем домашние работы
avdom = np.mean(marks_dom, axis=1) #находим средние по домашним по каждой строке

In [83]:
kolokv = marks[:, -1] #выделяем коллоквиум
prenakop = np.vstack((avprov, avdom, kolokv)) #создаем массив со столбцами = средняя за проверочную, средняя за домашнюю, коллоквиум

In [84]:
nakops = np.dot(weights, prenakop) #создаем массив с накопленными оценками, перемножая матрицу и вектор
nakops = nakops.reshape(num_studs, 1) #из строки переводим в столбец
nakops

array([[3.53      ],
       [3.53      ],
       [8.23857143],
       [5.72238095],
       [6.1247619 ],
       [9.2       ],
       [8.96380952],
       [1.5       ],
       [9.46761905],
       [8.56333333],
       [1.90857143],
       [9.21809524],
       [0.        ],
       [8.71714286],
       [8.63428571],
       [1.34      ],
       [9.96      ],
       [3.77952381],
       [0.        ],
       [1.43      ],
       [0.        ],
       [8.51714286],
       [9.78857143],
       [9.56666667],
       [3.04666667],
       [4.84      ],
       [9.01190476],
       [8.81666667]])

In [85]:
marks = np.hstack((marks, nakops)) #добавляем столбец накопленных оценок справа к исходному массиву

In [86]:
marks

array([[10.        ,  8.        , 10.        ,  0.        ,  0.        ,
         2.1       ,  1.5       ,  3.53      ],
       [ 0.        ,  6.        ,  4.4       ,  4.        ,  0.        ,
         5.        ,  4.3       ,  3.53      ],
       [ 4.28571429,  7.        ,  8.7       ,  7.6       ,  7.        ,
         9.7       , 10.        ,  8.23857143],
       [ 4.85714286,  1.3       ,  7.        ,  3.4       ,  0.        ,
         9.4       ,  9.        ,  5.72238095],
       [ 9.71428571,  9.1       ,  8.2       ,  0.        ,  0.        ,
         7.9       ,  7.9       ,  6.1247619 ],
       [10.        , 10.        , 10.        ,  9.        ,  9.5       ,
        10.        ,  8.        ,  9.2       ],
       [ 8.57142857, 10.        ,  9.7       ,  8.7       ,  7.        ,
         8.5       ,  9.7       ,  8.96380952],
       [ 0.        ,  9.3       ,  5.7       ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.5       ],
       [ 7.14285714, 10.        


### Студенты, которых, вероятно, отчислят (1.5 балла)

Сколько в группе студентов с накопленной оценкой 0? Вам может понадобиться тот факт, что применение np.sum к бинарному вектору дает число значений True в нем, например:

In [87]:
np.sum([True, False, True]) # 2 значения True

2

Также обратим внимание на операцию поэлементного сравнения, возвращающую массив из True и False:

In [88]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 3])
print(a == b)
print(a > b)

[False False  True]
[False False False]


In [89]:
zeronakop = nakops == 0 #создаем массив из логических выражений, показывающих наличие нулевой накопленной оценки

In [90]:
print(np.sum(zeronakop)) #находим число студентов с нулевым накопом

3


### Студенты, которые получат автоматы (1.5 балла)
Автомат получат студенты, у которых накопленная оценка больше 7. Добавьте еще один столбец - в нем стоит 1, если студент получает автомат, и 0 иначе.

In [91]:
avtomats = nakops > 7 #создаем массив из логических выражений, показывающих наличие накопа выше 7

In [92]:
biavtomats = 1 * avtomats #создаем массив из нулей и единиц, где 1 соответствует накопу выше 7
biavtomats = biavtomats.reshape(num_studs, 1) #превращаем строку в столбец

In [93]:
marks = np.hstack((marks, biavtomats)) #добавляем столбец из нулей и единиц к матрице с оценками

In [94]:
marks

array([[10.        ,  8.        , 10.        ,  0.        ,  0.        ,
         2.1       ,  1.5       ,  3.53      ,  0.        ],
       [ 0.        ,  6.        ,  4.4       ,  4.        ,  0.        ,
         5.        ,  4.3       ,  3.53      ,  0.        ],
       [ 4.28571429,  7.        ,  8.7       ,  7.6       ,  7.        ,
         9.7       , 10.        ,  8.23857143,  1.        ],
       [ 4.85714286,  1.3       ,  7.        ,  3.4       ,  0.        ,
         9.4       ,  9.        ,  5.72238095,  0.        ],
       [ 9.71428571,  9.1       ,  8.2       ,  0.        ,  0.        ,
         7.9       ,  7.9       ,  6.1247619 ,  0.        ],
       [10.        , 10.        , 10.        ,  9.        ,  9.5       ,
        10.        ,  8.        ,  9.2       ,  1.        ],
       [ 8.57142857, 10.        ,  9.7       ,  8.7       ,  7.        ,
         8.5       ,  9.7       ,  8.96380952,  1.        ],
       [ 0.        ,  9.3       ,  5.7       ,  0.        ,  0

### Студенты, которые будут освобождены от задач на экзамене (1.5 балла)
Семинарист решил, что первая половина группы в рейтинге по накопленной оценке будет освобождена от решения задач на экзамене. Выделите этих студентов в отдельный массив. Для этого надо отсортировать строки массива (np.sort) и взять первую половину.

In [95]:
markis_sort = marks[marks[:, -2].argsort()]#сортируем по  столбцу накопленных оценок - по возрастанию

In [96]:
marks_sort = markis_sort[::-1]#сортируем по убыванию накопов

In [97]:
pip = int(num_studs / 2) #находим половину студентов

In [98]:
new_marks = marks_sort[:pip] #выделяем половину студентов по рейтингу накопов

In [99]:
new_marks

array([[10.        , 10.        , 10.        ,  9.7       , 10.        ,
        10.        , 10.        ,  9.96      ,  1.        ],
       [ 9.28571429,  8.7       ,  9.5       , 10.5       ,  9.8       ,
        10.        , 10.        ,  9.78857143,  1.        ],
       [10.        ,  9.7       , 10.        ,  8.1       , 10.        ,
        10.        ,  9.5       ,  9.56666667,  1.        ],
       [ 7.14285714, 10.        , 10.        ,  9.9       , 10.5       ,
        10.        ,  9.        ,  9.46761905,  1.        ],
       [ 5.71428571, 10.        , 10.        ,  9.9       ,  9.7       ,
        10.        ,  9.        ,  9.21809524,  1.        ],
       [10.        , 10.        , 10.        ,  9.        ,  9.5       ,
        10.        ,  8.        ,  9.2       ,  1.        ],
       [ 4.28571429,  8.7       , 10.        ,  9.4       , 10.7       ,
        10.        ,  9.        ,  9.01190476,  1.        ],
       [ 8.57142857, 10.        ,  9.7       ,  8.7       ,  7

### Сложность заданий (1.5 балла)
Наконец, семинарист хочет оценить сложность заданий, проверочных и коллоквиума по своей особой системе. Он присвоил каждому студенту вес (веса суммируются в 1) и хочет посчитать для каждого задания, проверочной и коллоквиума среднюю оценку с весами.
Пример, что имеется в виду: если есть 4 студента с весами [0.1, 0.2, 0.3, 0.4] и оценками [3, 7, 9, 10], то средняя оценка за задание с весами получится 

In [100]:
0.1 * 3 + 0.2 * 7 + 0.3 * 9 + 0.4 * 10 

8.4

Веса:

In [101]:
weights = np.array([1.]*7+[2.]*4+[3.]*7+[4.]*(marks.shape[0]-18))
# разделите веса на их сумму, чтобы они суммировались к 1
weights = weights = (1 / np.sum(weights) * weights) 

In [102]:
weights

array([0.01315789, 0.01315789, 0.01315789, 0.01315789, 0.01315789,
       0.01315789, 0.01315789, 0.02631579, 0.02631579, 0.02631579,
       0.02631579, 0.03947368, 0.03947368, 0.03947368, 0.03947368,
       0.03947368, 0.03947368, 0.03947368, 0.05263158, 0.05263158,
       0.05263158, 0.05263158, 0.05263158, 0.05263158, 0.05263158,
       0.05263158, 0.05263158, 0.05263158])

Посчитайте указанным образом сложность каждого "столбца".

In [103]:
tasks = marks[:, :7] #выделяем только столбцы оценок по всем работам

In [104]:
weights = weights.reshape(1, num_studs) #превращаем столбец в строку

In [105]:
difficult = np.dot(weights, tasks) #находим сложность через умножение весов на оценки
difficult

array([[4.90037594, 7.11973684, 7.85789474, 6.16447368, 4.83289474,
        5.87894737, 4.87368421]])